spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bot_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

logging:
  config: classpath:\log\logback-config.xml
